import XCTest
@testable import QudelixBar

/// Importing a correction from pasted text. The parsing is shared with the
/// file path and already covered; what is new here is that the input is
/// arbitrary clipboard contents, which is a much less friendly thing than a
/// file someone deliberately chose.
@MainActor
final class ImportTextTests: XCTestCase {

    private func connected() -> QudelixController {
        let c = QudelixController()
        c.connection = .connected(name: "Qudelix 5K")
        c.compatibility = .ok
        return c
    }

    private let realCorrection = """
        Preamp: -6.1 dB
        Filter 1: ON LSC Fc 105 Hz Gain 6.4 dB Q 0.70
        Filter 2: ON PK Fc 8800 Hz Gain 5.1 dB Q 1.42
        Filter 3: ON PK Fc 118 Hz Gain -3.1 dB Q 0.50
        """

    func testAPastedCorrectionIsApplied() {
        let c = connected()
        c.importText(realCorrection)
        XCTAssertEqual(c.preGain, -6.1, accuracy: 0.05)
        XCTAssertEqual(c.bands[0].freq, 105)
        XCTAssertEqual(c.bands[0].filter, .lowShelf)
        XCTAssertEqual(c.bands[1].gain, 5.1, accuracy: 0.05)
    }

    /// A clipboard holds whatever was last copied. None of this should reach
    /// the device, and none of it should look like a failure of the app.
    func testTextThatIsNotACorrectionChangesNothing() {
        for junk in ["", "   \n\n  ", "hello world",
                     "https://example.com/some/page",
                     "{\"json\": true}",
                     "Preamp: -6.1 dB"] {          // a preamp with no filters
            let c = connected()
            let before = c.bands
            c.importText(junk)
            XCTAssertEqual(c.bands, before, "junk changed the curve: \(junk.prefix(20))")
            XCTAssertNotNil(c.lastImportSummary, "and it must say why")
        }
    }

    /// The clipboard can hold a whole document. The cap is the same one the
    /// file path uses, so a pasted novel is refused rather than parsed.
    func testAbsurdlyLargeTextIsRefused() {
        let c = connected()
        let before = c.bands
        c.importText(String(repeating: "Filter 1: ON PK Fc 100 Hz Gain 1 dB Q 1\n",
                            count: 40_000))
        XCTAssertEqual(c.bands, before)
        XCTAssertEqual(c.lastImportSummary, "That is too much text to be an EQ preset.")
    }

    /// A clipboard has no name, and inventing one would put a label on a preset
    /// slot that nothing stands behind — slot naming reads exactly this.
    func testPastedTextLeavesNoSourceNameToStampOnASlot() {
        let c = connected()
        c.importText(realCorrection)
        XCTAssertNil(QudelixController.nameOnSave(source: nil, existing: nil,
                                                  unchangedSinceSource: true))
    }

    /// Real pages wrap the filter list in surrounding prose; the parser should
    /// take the lines it recognises and ignore the rest.
    func testFiltersAreFoundAmongSurroundingText() {
        let c = connected()
        c.importText("""
            Recommended settings for the HD 650
            Use these values in your equaliser:

            \(realCorrection)

            Generated by some tool, 2026
            """)
        XCTAssertEqual(c.bands[0].freq, 105)
        XCTAssertEqual(c.preGain, -6.1, accuracy: 0.05)
    }

    private func scratchDirectory() throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("import-file-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        addTeardownBlock { try? FileManager.default.removeItem(at: dir) }
        return dir
    }

    func testAFileOnDiskIsAppliedAndNamesTheSlotSource() throws {
        let dir = try scratchDirectory()
        let url = dir.appendingPathComponent("HD 650.txt")
        try Data(realCorrection.utf8).write(to: url)

        let c = connected()
        c.importFile(at: url)
        XCTAssertEqual(c.bands[0].freq, 105)
        XCTAssertEqual(c.preGain, -6.1, accuracy: 0.05)
    }

    func testAnOversizedFileIsRefusedRatherThanRead() throws {
        let dir = try scratchDirectory()
        let url = dir.appendingPathComponent("huge.txt")
        try Data(repeating: 0x41, count: QudelixController.maxImportBytes + 1).write(to: url)

        let c = connected()
        let before = c.bands
        c.importFile(at: url)
        XCTAssertEqual(c.bands, before)
        XCTAssertNotNil(c.lastImportSummary)
    }

    func testASymlinkedFileIsNotFollowed() throws {
        let dir = try scratchDirectory()
        let real = dir.appendingPathComponent("real.txt")
        try Data(realCorrection.utf8).write(to: real)
        let link = dir.appendingPathComponent("link.txt")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: real)

        let c = connected()
        let before = c.bands
        c.importFile(at: link)
        XCTAssertEqual(c.bands, before, "a link is not a file this app agreed to read")
    }

    func testAFifoIsRefusedInsteadOfBlockingForever() throws {
        let dir = try scratchDirectory()
        let fifo = dir.appendingPathComponent("pipe.txt")
        let made = fifo.withUnsafeFileSystemRepresentation { path -> Int32 in
            guard let path else { return -1 }
            return mkfifo(path, 0o600)
        }
        XCTAssertEqual(made, 0, "could not create the FIFO this test is about")

        let c = connected()
        let before = c.bands
        c.importFile(at: fifo)
        XCTAssertEqual(c.bands, before)
    }

    func testWhatTheFileAskedForAndDidNotGetIsSaidOutLoud() {
        let c = connected()
        c.importText("""
            Preamp: -18.0 dB
            Filter 1: ON BP Fc 1000 Hz Gain 3.0 dB Q 1.0
            Filter 2: ON PK Fc 2000 Hz Gain -20.0 dB Q 1.0
            """)
        let summary = c.lastImportSummary ?? ""
        XCTAssertTrue(summary.contains("Applied 1 band(s)"), summary)
        XCTAssertTrue(summary.contains("skipped 1 filter line"), summary)
        XCTAssertTrue(summary.contains("pre-gain"), summary)
        XCTAssertTrue(summary.contains("clamped"), summary)
    }

    func testACleanFileGetsNoExtraNoise() {
        let c = connected()
        c.importText(realCorrection)
        XCTAssertEqual(c.lastImportSummary, "Applied 3 band(s), pre-gain -6.1 dB")
    }

    func testNothingIsAppliedWhileDisconnected() {
        let c = QudelixController()
        let before = c.bands
        c.importText(realCorrection)
        XCTAssertEqual(c.bands, before)
    }
}
