name: macOS

on:
  push:
    branches:
      - main
      - linux
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: swift build
        working-directory: QudelixBar

      - name: Test
        run: swift test
        working-directory: QudelixBar
